@startwbs
<style>
    node {
        lineColor: #FF0000;
        backgroundColor: #FFF8DC;
    }

    arrow {
        lineColor: #FF0000;
    }
</style>
skinparam shadowing true


* Сдача лабораторной работы
** Подготовка
*** Повторить материал лекций
*** Прочитать задания к работе
*** Подготовить справочные материалы
** Выполнение
*** Выполненить задание
*** Сделать отчет
** Защита
*** Ответить на вопросы
*** Выполнить дополнительное задание
@endwbs
