@startuml

activate "Партнер\n"
"Партнер\n" -> "Клиент\n": Привлечь клиента\nна сайт магазина

activate "Клиент\n"
"Клиент\n" -> "Клиент\n" : сохр. Cookie (+ сессию) -\nпроверка Cookie при\nкаждом обращении \nк сайту!

activate "Интернет-\nмагазин"
activate "Order\nmanager"
"Клиент\n" -> "Интернет-\nмагазин" : Оформить покупку
"Клиент\n" -> "Order\nmanager" : Отменить заказ
"Order\nmanager" --> "Интернет-\nмагазин" : Передать статус оплаты заказа (сразу)
"Интернет-\nмагазин" -[hidden]> "Интернет-\nмагазин"
deactivate "Клиент\n"
deactivate "Order\nmanager"
deactivate "Интернет-\nмагазин"

"Интернет-\nмагазин" -[hidden]> "Интернет-\nмагазин"
activate "Интернет-\nмагазин"
"Интернет-\nмагазин" -> "Интернет-\nмагазин" : CRON: сделать расчет\nпартнерской программы:\nкаждые 5 минут

' "Интернет-\nмагазин" -[hidden]> "Интернет-\nмагазин"
deactivate "Интернет-\nмагазин"

note left
    Расчеты
    фиксируются в
    таблице
    paymentsLog.

    При открытии отчета
    "Регистрация
    выплат"
    сравнивается сумма
    начислений и сумма
    выплат. Если
    разница в пользу
    партнера - он
    попадает в этот
    отчет.
end note

activate "Менеджер Интернет-\nмагазина"
"Интернет-\nмагазин" -[hidden]> "Интернет-\nмагазин"
activate "Интернет-\nмагазин"
"Менеджер Интернет-\nмагазина" -> "Интернет-\nмагазин" : Регистрировать выплаты (каждое 1-ое число месяца)
"Интернет-\nмагазин" -[hidden]> "Интернет-\nмагазин"
deactivate "Менеджер Интернет-\nмагазина"
"Интернет-\nмагазин" -> "Партнер\n" : Произвести выплаты (каждое 1-ое число месяца)

@enduml